version: '3'
services:
  nginx:
    restart: always
    image:
      'nginx:latest'
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    depends_on:
      -  api
      -  client

  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - '/app/node_modules'
      - './server:/app'
    environment:
      - MONGO_USER=disha_2601
      - MONGO_PASSWORD=Disha26@nov
    command: ["npm", "run", "server"] 
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - '/app/node_modules'
      - './client:/app'
    command: ["npm", "start"]
    tty: true
  